-- PostgreSQL schema for GestionClub
CREATE TABLE IF NOT EXISTS clubes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  ciudad VARCHAR(255) NOT NULL,
  liga VARCHAR(255) NOT NULL,
  estadio VARCHAR(255) NOT NULL,
  presupuesto DECIMAL(12,2) NOT NULL DEFAULT 0,
  escudo_url VARCHAR(500),
  estado VARCHAR(50) DEFAULT 'Activo',
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  rol VARCHAR(20) DEFAULT 'usuario' CHECK (rol IN ('admin', 'tesorero', 'usuario')),
  club_id INTEGER,
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS temporadas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(20) NOT NULL UNIQUE,
  anio_inicio INTEGER NOT NULL,
  anio_fin INTEGER NOT NULL,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NOT NULL,
  activo BOOLEAN DEFAULT TRUE,
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ingresos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL,
  club_id INTEGER NOT NULL,
  fecha DATE NOT NULL,
  concepto VARCHAR(255) NOT NULL,
  monto DECIMAL(10,2) NOT NULL,
  iva DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  total_con_iva DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  descripcion TEXT,
  temporada VARCHAR(20) DEFAULT '2024/25',
  cuenta_id INTEGER,
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS conceptos_ingresos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id INTEGER NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  descripcion TEXT,
  iva DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  activo BOOLEAN DEFAULT TRUE,
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_conceptos_ingresos_club_nombre
  ON conceptos_ingresos (club_id, nombre);

CREATE TABLE IF NOT EXISTS egresos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL,
  club_id INTEGER NOT NULL,
  fecha DATE NOT NULL,
  concepto VARCHAR(255) NOT NULL,
  monto DECIMAL(10,2) NOT NULL,
  categoria VARCHAR(255) NOT NULL,
  iva DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  total_con_iva DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  descripcion TEXT,
  temporada VARCHAR(20) DEFAULT '2024/25',
  cuenta_id INTEGER,
  cuenta_origen_id INTEGER,
  cuenta_destino_id INTEGER,
  es_traspaso BOOLEAN NOT NULL DEFAULT FALSE,
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jugadores (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id INTEGER NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  posicion VARCHAR(30) NOT NULL CHECK (posicion IN ('Portero','Defensa','Centrocampista','Delantero')),
  numero INTEGER NOT NULL,
  estado VARCHAR(20) DEFAULT 'Activo' CHECK (estado IN ('Activo','Lesionado','Retirado')),
  fecha_incorporacion DATE,
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS eventos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id INTEGER NOT NULL,
  fecha DATE NOT NULL,
  hora TIME NOT NULL,
  tipo VARCHAR(50) NOT NULL CHECK (tipo IN ('Partido','Entrenamiento','Asamblea','Evento Social','Otro')),
  descripcion VARCHAR(255) NOT NULL,
  ubicacion VARCHAR(255),
  temporada VARCHAR(20) DEFAULT '2024/25',
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cuentas_bancarias (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id INTEGER NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  tipo VARCHAR(30) NOT NULL DEFAULT 'Banco',
  banco VARCHAR(255) NOT NULL,
  numero_cuenta VARCHAR(100) NOT NULL,
  iban VARCHAR(100),
  saldo_inicial DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  fecha_saldo_inicial DATE NOT NULL DEFAULT CURRENT_DATE,
  saldo DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  activo BOOLEAN DEFAULT TRUE,
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_cuentas_bancarias_club_nombre
  ON cuentas_bancarias (club_id, nombre);

CREATE TABLE IF NOT EXISTS saldos_cuentas_mensuales (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  club_id INTEGER NOT NULL,
  cuenta_id INTEGER NOT NULL,
  temporada VARCHAR(20) NOT NULL,
  mes INTEGER NOT NULL CHECK (mes BETWEEN 1 AND 12),
  fecha_inicio DATE NOT NULL,
  fecha_cierre DATE NOT NULL,
  saldo_inicial DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  total_ingresos DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  total_egresos DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  saldo_final DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  fecha_calculo TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_saldos_cuentas_mensuales UNIQUE (club_id, cuenta_id, temporada, mes)
);

INSERT INTO clubes (nombre, ciudad, liga, estadio, presupuesto, escudo_url, estado)
VALUES
  ('Real Madrid CF', 'Madrid', 'LaLiga', 'Santiago Bernabéu', 240000000, 'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg', 'Activo'),
  ('FC Barcelona', 'Barcelona', 'LaLiga', 'Camp Nou', 210000000, 'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg', 'Activo'),
  ('Bayern Munich', 'Múnich', 'Bundesliga', 'Allianz Arena', 190000000, 'https://upload.wikimedia.org/wikipedia/commons/1/12/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg', 'Activo')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO usuarios (email, nombre, password, rol, club_id)
VALUES ('admin@club.com', 'admin', '$2a$10$YourHashedPasswordHere', 'admin', 1)
ON CONFLICT (email) DO NOTHING;
