import pg from 'pg';
import bcrypt from 'bcryptjs';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const { Pool } = pg;

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.resolve(__dirname, '.env') });

const connection = new Pool({
  host: process.env.DB_HOST || 'localhost',
  port: Number(process.env.DB_PORT || 5432),
  user: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASSWORD || '',
  database: process.env.DB_NAME || process.env.DB_DATABASE || 'gestionclub',
  max: 10,
  idleTimeoutMillis: 30000,
  connectionTimeoutMillis: 10000,
  ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false
});

const ensureTable = async (client, table, createSql) => {
  const { rows } = await client.query(
    `SELECT to_regclass($1) AS table_exists`,
    [table]
  );

  if (!rows[0]?.table_exists) {
    await client.query(createSql);
    console.log(`CREATED TABLE ${table}`);
  } else {
    console.log(`EXISTS TABLE ${table}`);
  }
};

const ensureColumn = async (client, table, column, definition) => {
  const { rows } = await client.query(
    `SELECT column_name
     FROM information_schema.columns
     WHERE table_schema = current_schema()
       AND table_name = $1
       AND column_name = $2`,
    [table, column]
  );

  if (rows.length === 0) {
    await client.query(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
    console.log(`ADDED ${table}.${column}`);
  } else {
    console.log(`EXISTS ${table}.${column}`);
  }
};

const withClient = async (callback) => {
  const client = await connection.connect();
  try {
    return await callback(client);
  } finally {
    client.release();
  }
};

try {
  await withClient(async (client) => {
    await ensureTable(client, 'clubes', `CREATE TABLE clubes (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nombre VARCHAR(255) NOT NULL,
      ciudad VARCHAR(255) NOT NULL,
      liga VARCHAR(255) NOT NULL,
      estadio VARCHAR(255) NOT NULL,
      presupuesto DECIMAL(12,2) NOT NULL DEFAULT 0,
      escudo_url VARCHAR(500),
      estado VARCHAR(50) DEFAULT 'Activo',
      fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`);
    await client.query(`CREATE UNIQUE INDEX IF NOT EXISTS uk_clubes_nombre ON clubes (nombre)`);
    await ensureColumn(client, 'clubes', 'escudo_url', 'VARCHAR(500)');

    await ensureTable(client, 'usuarios', `CREATE TABLE usuarios (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email VARCHAR(255) UNIQUE NOT NULL,
      nombre VARCHAR(255) NOT NULL,
      password VARCHAR(255) NOT NULL,
      rol VARCHAR(20) DEFAULT 'usuario' CHECK (rol IN ('admin', 'tesorero', 'usuario')),
      club_id INTEGER,
      fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      activo BOOLEAN DEFAULT TRUE
    )`);

    await ensureTable(client, 'temporadas', `CREATE TABLE temporadas (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nombre VARCHAR(20) NOT NULL UNIQUE,
      anio_inicio INTEGER NOT NULL,
      anio_fin INTEGER NOT NULL,
      fecha_inicio DATE NOT NULL,
      fecha_fin DATE NOT NULL,
      activo BOOLEAN DEFAULT TRUE,
      fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`);

    await ensureColumn(client, 'temporadas', 'nombre', 'VARCHAR(20) NOT NULL UNIQUE');
    await ensureColumn(client, 'temporadas', 'anio_inicio', 'INTEGER NOT NULL');
    await ensureColumn(client, 'temporadas', 'anio_fin', 'INTEGER NOT NULL');
    await ensureColumn(client, 'temporadas', 'fecha_inicio', 'DATE NOT NULL');
    await ensureColumn(client, 'temporadas', 'fecha_fin', 'DATE NOT NULL');
    await ensureColumn(client, 'temporadas', 'activo', 'BOOLEAN DEFAULT TRUE');

    const temporadaActual = new Date();
    const anioInicioTemporada = temporadaActual.getMonth() >= 6 ? temporadaActual.getFullYear() : temporadaActual.getFullYear() - 1;
    const nombreTemporadaActual = `${anioInicioTemporada}/${String(anioInicioTemporada + 1).slice(-2)}`;
    const fechaInicioTemporada = new Date(Date.UTC(anioInicioTemporada, 6, 1));
    const fechaFinTemporada = new Date(Date.UTC(anioInicioTemporada + 1, 5, 30));

    await client.query(
      `INSERT INTO temporadas (nombre, anio_inicio, anio_fin, fecha_inicio, fecha_fin, activo)
       VALUES ($1, $2, $3, $4, $5, TRUE)
       ON CONFLICT (nombre) DO UPDATE SET
         anio_inicio = EXCLUDED.anio_inicio,
         anio_fin = EXCLUDED.anio_fin,
         fecha_inicio = EXCLUDED.fecha_inicio,
         fecha_fin = EXCLUDED.fecha_fin,
         activo = TRUE`,
      [nombreTemporadaActual, anioInicioTemporada, anioInicioTemporada + 1, fechaInicioTemporada.toISOString().slice(0, 10), fechaFinTemporada.toISOString().slice(0, 10)]
    );

    await ensureTable(client, 'ingresos', `CREATE TABLE ingresos (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      usuario_id INTEGER NOT NULL,
      club_id INTEGER NOT NULL,
      fecha DATE NOT NULL,
      concepto VARCHAR(255) NOT NULL,
      monto DECIMAL(10,2) NOT NULL,
      iva DECIMAL(5,2) NOT NULL DEFAULT 0.00,
      total_con_iva DECIMAL(10,2) NOT NULL DEFAULT 0.00,
      descripcion TEXT,
      fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`);

    const fechaActual = new Date();
    const anioActual = fechaActual.getFullYear();
    const temporadaBase = fechaActual.getMonth() >= 6 ? anioActual : anioActual - 1;
    const temporadaPredeterminada = `${temporadaBase}/${String(temporadaBase + 1).slice(-2)}`;

    await ensureColumn(client, 'ingresos', 'iva', 'DECIMAL(5,2) NOT NULL DEFAULT 0.00');
    await ensureColumn(client, 'ingresos', 'total_con_iva', 'DECIMAL(10,2) NOT NULL DEFAULT 0.00');
    await ensureColumn(client, 'ingresos', 'cuenta_id', 'INTEGER');
    await ensureColumn(client, 'ingresos', 'temporada', `VARCHAR(20) NOT NULL DEFAULT '${temporadaPredeterminada}'`);
    await client.query(`UPDATE ingresos SET temporada = $1 WHERE temporada IS NULL OR temporada = ''`, [temporadaPredeterminada]);

    await ensureTable(client, 'conceptos_ingresos', `CREATE TABLE conceptos_ingresos (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      club_id INTEGER NOT NULL,
      nombre VARCHAR(255) NOT NULL,
      descripcion TEXT,
      iva DECIMAL(5,2) NOT NULL DEFAULT 0.00,
      activo BOOLEAN DEFAULT TRUE,
      fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`);
    await client.query(`CREATE UNIQUE INDEX IF NOT EXISTS uk_conceptos_ingresos_club_nombre ON conceptos_ingresos (club_id, nombre)`);

    await ensureTable(client, 'conceptos_egresos', `CREATE TABLE conceptos_egresos (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      club_id INTEGER NOT NULL,
      nombre VARCHAR(255) NOT NULL,
      descripcion TEXT,
      iva DECIMAL(5,2) NOT NULL DEFAULT 0.00,
      activo BOOLEAN DEFAULT TRUE,
      fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`);
    await client.query(`CREATE UNIQUE INDEX IF NOT EXISTS uk_conceptos_egresos_club_nombre ON conceptos_egresos (club_id, nombre)`);

    await ensureTable(client, 'egresos', `CREATE TABLE egresos (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      usuario_id INTEGER NOT NULL,
      club_id INTEGER NOT NULL,
      fecha DATE NOT NULL,
      concepto VARCHAR(255) NOT NULL,
      monto DECIMAL(10,2) NOT NULL,
      categoria VARCHAR(255) NOT NULL,
      iva DECIMAL(5,2) NOT NULL DEFAULT 0.00,
      total_con_iva DECIMAL(10,2) NOT NULL DEFAULT 0.00,
      descripcion TEXT,
      fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`);

    await ensureColumn(client, 'egresos', 'iva', 'DECIMAL(5,2) NOT NULL DEFAULT 0.00');
    await ensureColumn(client, 'egresos', 'total_con_iva', 'DECIMAL(10,2) NOT NULL DEFAULT 0.00');
    await ensureColumn(client, 'egresos', 'cuenta_id', 'INTEGER');
    await ensureColumn(client, 'egresos', 'cuenta_origen_id', 'INTEGER');
    await ensureColumn(client, 'egresos', 'cuenta_destino_id', 'INTEGER');
    await ensureColumn(client, 'egresos', 'es_traspaso', 'BOOLEAN NOT NULL DEFAULT FALSE');
    await ensureColumn(client, 'egresos', 'temporada', `VARCHAR(20) NOT NULL DEFAULT '${temporadaPredeterminada}'`);
    await client.query(`UPDATE egresos SET temporada = $1 WHERE temporada IS NULL OR temporada = ''`, [temporadaPredeterminada]);

    await ensureTable(client, 'jugadores', `CREATE TABLE jugadores (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      club_id INTEGER NOT NULL,
      nombre VARCHAR(255) NOT NULL,
      posicion VARCHAR(30) NOT NULL CHECK (posicion IN ('Portero','Defensa','Centrocampista','Delantero')),
      numero INTEGER NOT NULL,
      estado VARCHAR(20) DEFAULT 'Activo' CHECK (estado IN ('Activo','Lesionado','Retirado')),
      fecha_incorporacion DATE,
      fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`);

    await ensureTable(client, 'eventos', `CREATE TABLE eventos (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      club_id INTEGER NOT NULL,
      fecha DATE NOT NULL,
      hora TIME NOT NULL,
      tipo VARCHAR(50) NOT NULL CHECK (tipo IN ('Partido','Entrenamiento','Asamblea','Evento Social','Otro')),
      descripcion VARCHAR(255) NOT NULL,
      ubicacion VARCHAR(255),
      temporada VARCHAR(20) NOT NULL DEFAULT '${temporadaPredeterminada}',
      fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`);

    await ensureTable(client, 'cuentas_bancarias', `CREATE TABLE cuentas_bancarias (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      club_id INTEGER NOT NULL,
      nombre VARCHAR(255) NOT NULL,
      tipo VARCHAR(30) NOT NULL DEFAULT 'Banco',
      banco VARCHAR(255) NOT NULL,
      numero_cuenta VARCHAR(100) NOT NULL,
      iban VARCHAR(100),
      saldo DECIMAL(12,2) NOT NULL DEFAULT 0.00,
      activo BOOLEAN DEFAULT TRUE,
      fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )`);
    await client.query(`CREATE UNIQUE INDEX IF NOT EXISTS uk_cuentas_bancarias_club_nombre ON cuentas_bancarias (club_id, nombre)`);

    await ensureColumn(client, 'cuentas_bancarias', 'tipo', 'VARCHAR(30) NOT NULL DEFAULT \'Banco\'');
    await ensureColumn(client, 'eventos', 'temporada', `VARCHAR(20) NOT NULL DEFAULT '${temporadaPredeterminada}'`);
    await client.query(`UPDATE eventos SET temporada = $1 WHERE temporada IS NULL OR temporada = ''`, [temporadaPredeterminada]);
    await ensureColumn(client, 'usuarios', 'club_id', 'INTEGER');
    await ensureColumn(client, 'ingresos', 'club_id', 'INTEGER NOT NULL DEFAULT 1');
    await ensureColumn(client, 'egresos', 'club_id', 'INTEGER NOT NULL DEFAULT 1');
    await ensureColumn(client, 'jugadores', 'club_id', 'INTEGER NOT NULL DEFAULT 1');
    await ensureColumn(client, 'eventos', 'club_id', 'INTEGER NOT NULL DEFAULT 1');

    const { rows: clubs } = await client.query('SELECT id FROM clubes ORDER BY id LIMIT 1');
    const defaultClub = clubs[0]?.id || 1;

    await client.query(
      `INSERT INTO clubes (nombre, ciudad, liga, estadio, presupuesto, estado)
       VALUES ($1, $2, $3, $4, $5, $6)
       ON CONFLICT (nombre) DO NOTHING`,
      ['Real Madrid CF', 'Madrid', 'LaLiga', 'Santiago Bernabéu', 240000000, 'Activo']
    );

    const { rows: freshClub } = await client.query('SELECT id FROM clubes ORDER BY id LIMIT 1');
    const actualDefaultClub = freshClub[0]?.id || defaultClub;

    await client.query('UPDATE usuarios SET club_id = $1 WHERE club_id IS NULL OR club_id = 0', [actualDefaultClub]);
    await client.query('UPDATE ingresos SET club_id = $1 WHERE club_id IS NULL OR club_id = 0', [actualDefaultClub]);
    await client.query('UPDATE egresos SET club_id = $1 WHERE club_id IS NULL OR club_id = 0', [actualDefaultClub]);
    await client.query('UPDATE jugadores SET club_id = $1 WHERE club_id IS NULL OR club_id = 0', [actualDefaultClub]);
    await client.query('UPDATE eventos SET club_id = $1 WHERE club_id IS NULL OR club_id = 0', [actualDefaultClub]);

    const adminPasswordHash = bcrypt.hashSync('admin123', 10);

    await client.query(
      `INSERT INTO usuarios (email, nombre, password, rol, club_id)
       VALUES ($1, $2, $3, $4, $5)
       ON CONFLICT (email) DO UPDATE SET
         password = EXCLUDED.password,
         nombre = EXCLUDED.nombre,
         rol = EXCLUDED.rol,
         club_id = EXCLUDED.club_id`,
      ['admin@club.com', 'admin', adminPasswordHash, 'admin', actualDefaultClub]
    );

    const { rows: columns } = await client.query(
      `SELECT table_name, column_name
       FROM information_schema.columns
       WHERE table_schema = current_schema() AND column_name = $1`,
      ['club_id']
    );

    console.log('club_id columns:', JSON.stringify(columns, null, 2));
  });
} finally {
  await connection.end();
}
